# Generated by Django 5.2.8 on 2025-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='รายละเอียดงาน')),
                ('start_date', models.DateField(verbose_name='วันที่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
