"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# เพิ่มบรรทัดนี้เพื่อใช้ os.path
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+1eyhpj+5(=&1o&vr5-1_@0$o#!d27^es&lq7w5fo*5a*d&&8x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize', # เพิ่มแอป humanize เพื่อช่วยในการจัดรูปแบบตัวเลขและวันที่

    # เพิ่มชื่อแอปที่สร้างขึ้น
    'core',
    'accounts',
    'stores',
    'framings',
    'plaques',
    'cart',
]

#บอก Django ว่า "ตาราง User หลัก" ของโปรเจกต์นี้คือ 'accounts.CustomUser'
AUTH_USER_MODEL = 'accounts.CustomUser'

# ตั้งค่าสำหรับไฟล์ที่ผู้ใช้อัปโหลด
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ตั้งค่าสำหรับไฟล์สแตติกเก็บรูปตัวอย่างสินค้า
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # บอก Django ให้รู้จักโฟลเดอร์ templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'cart.context_processors.cart_count', # เพิ่ม context processor สำหรับตะกร้าสินค้า
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# แก้ไขการตั้งค่า DATABASES เพื่อใช้ MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wayustudio',      # << ชื่อฐานข้อมูลที่คุณสร้าง ใน Workbench
        'USER': 'root',                 # << ชื่อผู้ใช้ของ MySQL (default คือ root)
        'PASSWORD': '2547',             # << รหัสผ่าน
        'HOST': '127.0.0.1',            # << localhost หรือ 127.0.0.1 
        'PORT': '3306',                 # << พอร์ตของ MySQL (default คือ 3306) 
    }
}

# DATABASES เดิมใช้ SQLite3
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES เดิมใช้ SQLite3

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [] # ใช้แบบไม่มีการตรวจสอบรหัสผ่านในการ ทดสอบระบบ

#ลบออกเพื่อให้มีการตรวจสอบรหัสผ่าน
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#ลบออกเพื่อให้มีการตรวจสอบรหัสผ่าน

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
