# Generated by Django 5.2.8 on 2025-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaqueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ชื่อผู้สั่งทำ')),
                ('customer_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('deceased_name', models.CharField(max_length=200, verbose_name='ชื่อผู้วายชนม์ (บนป้าย)')),
                ('deceased_photo', models.ImageField(upload_to='plaques_photos/', verbose_name='รูปถ่าย')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปีเกิด')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปีมรณะ')),
                ('stone_style', models.CharField(choices=[('white_pearl', 'หินอ่อนขาวมุก'), ('black_granite', 'หินแกรนิตดำ'), ('pink_marble', 'หินอ่อนชมพู')], max_length=50, verbose_name='รูปแบบหิน')),
                ('size', models.CharField(choices=[('15x20', '15x20 ซม. (1,000 บาท)'), ('14x29', '14x29 ซม. (1,700 บาท)')], default='15x20', max_length=20, verbose_name='ขนาด')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('shipping_method', models.CharField(choices=[('pickup', 'รับสินค้าเองที่ร้าน (ฟรี)'), ('standard', 'ขนส่งธรรมดา (+50฿)'), ('express', 'ส่งด่วนพิเศษ (+100฿)')], default='pickup', max_length=20, verbose_name='วิธีจัดส่ง')),
                ('PAYMENT_SLIP', models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='สลิปโอนเงิน')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='ราคาป้าย (บาท)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาสุทธิ (รวมส่ง)')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ (แจ้งโอนแล้ว)'), ('processing', 'กำลังผลิต'), ('completed', 'ผลิตเสร็จแล้ว'), ('shipped', 'จัดส่งเรียบร้อย')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง')),
            ],
            options={
                'verbose_name': 'รายการสั่งทำป้าย',
                'verbose_name_plural': 'รายการสั่งทำป้ายทั้งหมด',
            },
        ),
    ]
