# Generated by Django 5.2.8 on 2025-11-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaqueorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='plaqueorder',
            name='customer_tel',
        ),
        migrations.AddField(
            model_name='plaqueorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งทำ (User ID)'),
        ),
    ]
