# Generated by Django 5.2.8 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0002_remove_plaqueorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaqueorder',
            name='PAYMENT_SLIP',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slipsorderplaques/%Y/%m/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AlterField(
            model_name='plaqueorder',
            name='deceased_photo',
            field=models.ImageField(upload_to='customer_plaquesuploads/%Y/%m/', verbose_name='รูปถ่าย'),
        ),
        migrations.AlterField(
            model_name='plaqueorder',
            name='stone_style',
            field=models.CharField(choices=[('black_granite', 'หินแกรนิตดำ')], max_length=50, verbose_name='รูปแบบหิน'),
        ),
    ]
