# Generated by Django 5.2.8 on 2025-11-24 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0003_alter_plaqueorder_payment_slip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaqueOrder',
            new_name='CustomPlaqueOrder',
        ),
    ]
