# Generated by Django 5.2.8 on 2025-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0004_rename_plaqueorder_customplaqueorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplaqueorder',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต/ตรวจสอบ'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
