# Generated by Django 5.2.8 on 2025-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0006_alter_customplaqueorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplaqueorder',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'โอนเงินผ่านธนาคาร')], default='transfer', max_length=20, verbose_name='วิธีชำระเงิน'),
        ),
    ]
