# Generated by Django 5.2.8 on 2025-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaques', '0007_customplaqueorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplaqueorder',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'รับเองที่ร้าน (ฟรี)'), ('standard', 'ขนส่งธรรมดา (50 บาท)'), ('express', 'ขนส่งด่วน (100 บาท)')], default='pickup', max_length=20, verbose_name='วิธีจัดส่ง'),
        ),
    ]
