# Generated by Django 5.2.8 on 2025-11-24 18:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อชิ้น')),
                ('shipping_method', models.CharField(choices=[('pickup', 'รับสินค้าเองที่ร้าน'), ('standard', 'ขนส่งธรรมดา'), ('express', 'ส่งด่วนพิเศษ')], default='pickup', max_length=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดสุทธิ')),
                ('payment_method', models.CharField(default='transfer', max_length=20, verbose_name='วิธีชำระเงิน')),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='payment_oaderslips/%Y/%m/', verbose_name='สลิปโอนเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน/รอตรวจสอบ'), ('confirmed', 'ยืนยันแล้ว'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาแก้ไขล่าสุด')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ลูกค้า')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
            },
        ),
    ]
