# Generated by Django 5.2.8 on 2025-12-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต/เตรียมพัสดุ'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
