# Generated by Django 5.2.8 on 2025-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'โอนเงินผ่านธนาคาร')], default='transfer', max_length=20, verbose_name='วิธีชำระเงิน'),
        ),
    ]
