# Generated by Django 5.2.8 on 2025-12-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'รับเองที่ร้าน (ฟรี)'), ('standard', 'ขนส่งธรรมดา (50 บาท)'), ('express', 'ขนส่งด่วน (100 บาท)')], default='pickup', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อชิ้น (ณ ตอนซื้อ)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในบิล',
                'verbose_name_plural': 'รายการสินค้าในบิล',
            },
        ),
    ]
