# Generated by Django 5.2.8 on 2025-11-19 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อลายกรอบ')),
                ('image', models.ImageField(upload_to='frame_styles/', verbose_name='รูปตัวอย่าง')),
                ('price_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='ตัวคูณราคา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFrameOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='customer_uploads/%Y/%m/', verbose_name='รูปจากลูกค้า')),
                ('size_option', models.CharField(choices=[('4x6', '4 x 6 นิ้ว'), ('A4', 'A4'), ('A3', 'A3')], max_length=10, verbose_name='ขนาด')),
                ('mounting_option', models.CharField(choices=[('stand', 'ขาตั้ง'), ('hanger', 'ที่แขวน'), ('both', 'ทั้งขาตั้งและที่แขวน')], max_length=10, verbose_name='การติดตั้ง')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคารวม')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ลูกค้า')),
                ('frame_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='framings.framestyle', verbose_name='ลายกรอบที่เลือก')),
            ],
        ),
    ]
