# Generated by Django 5.2.8 on 2025-11-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customframeorder',
            name='frame_style',
        ),
        migrations.DeleteModel(
            name='FrameStyle',
        ),
    ]
