# Generated by Django 5.2.8 on 2025-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0002_remove_customframeorder_frame_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customframeorder',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'โอนเงินผ่านธนาคาร'), ('cod', 'เก็บเงินปลายทาง (COD)')], default='transfer', max_length=10, verbose_name='วิธีชำระเงิน'),
        ),
        migrations.AddField(
            model_name='customframeorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/%Y/%m/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AddField(
            model_name='customframeorder',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'ขนส่งธรรมดา (50 บาท)'), ('express', 'ขนส่งด่วน (100 บาท)')], default='standard', max_length=10, verbose_name='วิธีจัดส่ง'),
        ),
        migrations.AddField(
            model_name='customframeorder',
            name='style_option',
            field=models.CharField(choices=[('wood', 'กรอบไม้'), ('glass', 'กรอบกระจก')], default='wood', max_length=20, verbose_name='รูปแบบกรอบ'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='size_option',
            field=models.CharField(choices=[('8x10', '8 x 10 นิ้ว'), ('10x12', '10 x 12 นิ้ว'), ('16x20', '16 x 20 นิ้ว')], max_length=10, verbose_name='ขนาด'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต/ตรวจสอบ'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
