# Generated by Django 5.2.8 on 2025-11-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0003_customframeorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customframeorder',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'โอนเงินผ่านธนาคาร')], default='transfer', max_length=10, verbose_name='วิธีชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slipscustomerframings/%Y/%m/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'รับเองที่ร้าน (ฟรี)'), ('standard', 'ขนส่งธรรมดา (50 บาท)'), ('express', 'ขนส่งด่วน (100 บาท)')], default='standard', max_length=10, verbose_name='วิธีจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='uploaded_image',
            field=models.ImageField(upload_to='customer_framingsuploads/%Y/%m/', verbose_name='รูปจากลูกค้า'),
        ),
    ]
