# Generated by Django 5.2.8 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0004_alter_customframeorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customframeorder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slipsorderframings/%Y/%m/', verbose_name='สลิปโอนเงิน'),
        ),
    ]
