# Generated by Django 5.2.8 on 2025-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0005_customframeorder_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customframeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต/เตรียมพัสดุ'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
